### DISCUSSION TITLE
IncludedLocations directive

### DISCUSSION THREAD

**Discussion by atovstonog** [prebid/line-item-manager#153] [General]
Is this feature available for includedLocations or is there only an excludedLocation for geotargeting?
When I try to use something like this - includedLocations I get the error KeyError: 'includedLocations'
Can anyone help me?

**Comment by dshore** [comment]
See this: [GeoTargeting](https://developers.google.com/ad-manager/api/reference/v202308/LineItemService.GeoTargeting)

See "line_item_manager create --help", you would need to use the "--template" option and provide your own custom line item template.

For example you could add this to your own custom template:
```
targeting:
  geoTargeting:
    excludedLocations:
      - id: 2840
        displayName: "United States"
```
