### ISSUE TITLE
Custom targeting of "CustomKey1 != True AND CustomKey2 != True"

### ISSUE THREAD

**Issue by dshore** [prebid/line-item-manager#35]
* line-item-manager version:
* Python version:
* Operating System:

### Background

For custom targeting the following is implemented:
- conjuctive "AND" operator is used across children:
  https://github.com/prebid/line-item-manager/blob/master/line_item_manager/conf.d/line_item_template.yml#L53
- children use "IS" operator, i.e. Key value "is any of":
  https://github.com/prebid/line-item-manager/blob/master/line_item_manager/conf.d/line_item_template.yml#L57
- Matching is "EXACT":
  https://github.com/prebid/line-item-manager/blob/master/line_item_manager/gam_config.py#L31

### Answer

Therefore to implement:  "CustomKey1 != True AND CustomKey2 != True" this seems logically correct:
```
targeting:
  custom: # list (optional)
    - name: "CustomKey1"
      values:
        - "False"
    - name: "CustomKey2"
      values:
        - "False"
```

### Enhancement:

The following which is not currently supported but could be added as a feature:

```
targeting:
  custom: # list (optional)
    - name: "CustomKey1"
      operator: "IS_NOT"
      values:
        - "True"
    - name: "CustomKey2"
      operator: "IS_NOT"
      values:
        - "True"
```
