### ISSUE TITLE
Support for same ad size being served several times on the same page

### ISSUE THREAD

**Issue by dshore** [prebid/line-item-manager#42]
* line-item-manager version:
* Python version:
* Operating System:

### Description

I would like to be able to do orders by size where each line item contains e.g. only 1 size.  In this example I would like to have many creatives but all are for one size only.

**Comment by dshore** [comment]
### Proposed Enhancement

Support configurations when "size_override" is False that allows user to specify the number of copies of the creative desired, eg:
```
creative: # at least one of the following types is required {video, banner}
  name: "Prebid {{ bidder_name }}-{{ media_type }}"
  banner:
    # safe_frame: False # optional: defaults to True
    size_override: False # optional: defaults to True with a 1x1 creative
    copies: 5
    sizes: # list
      - height: 480
        width: 640
    snippet: |
      <script src = "https://..."></script>
        <script>
          ...
        </script>
```
