### ISSUE TITLE
Certain currency values are invalid

### ISSUE THREAD

**Issue by dshore** [prebid/line-item-manager#73]
### Description

I configured a custom granularity with a minimum of 4.51

### What I Did

```
rate:
  currency: "USD" # required
  granularity:
    type: "custom" # required, choices: "low", "med", "high", "auto", "dense", "custom"
    custom:
      - min: 4.51
        max: 50.00
        interval: 0.01
```

### What happened

```
Error: Check your configfile for the following validation errors:
  - Path(rate, granularity, custom, 0, min): 4.51 is not a multiple of 0.01
```

**Comment by ocm-peter** [comment]
Same error for the below configuration:
```
rate:
  currency: "EUR" # required
  granularity:
    type: "custom" # required, choices: "low", "med", "high", "auto", "dense", "custom"
    custom: # optional, requires type "custom" above
      - min: 0.01
        max: 2.00
        interval: 0.01
      - min: 2.02
        max: 5.00
        interval: 0.02
      - min: 5.10
        max: 10.00
        interval: 0.10
      - min: 10.25
        max: 20.00
        interval: 0.25
```
