### ISSUE TITLE
Targeting by placement_names returns error "Placement was not found "

### ISSUE THREAD

**Issue by torontobros** [prebid/line-item-manager#75]
* line-item-manager version: 0.2.3
* Python version: 3.9.4
* Operating System: 10.0.19042 Build 19042

### Description

Trying to push line items with targeting specific **placement_names**. 

The placement does exist and the name is copy-pasted to avoid typos, however, i keep getting this:

ERROR:line_item_manager.cli:Not able to find the following resource:
  - Placement named 'Prebid Inventory' was not found

NOTE: tried other placement names too

### What I Did

```
###############################################################################
targeting:
  bidder: # object (optional)
    reportableType: "ON" # optional, defaults to "OFF", choices: "ON", "OFF", "CUSTOM_DIMENSION"
  # custom: # list (optional)
    # - name: "country"
      # operator: "IS_NOT" # optional: defaults to "IS"
      # values:
        # - "US"
        # - "CAN"
      # reportableType: "ON" # optional, defaults to "OFF", choices: "ON", "OFF", "CUSTOM_DIMENSION"
    # - name: "site"
      # operator: "IS_NOT" # optional: defaults to "IS"
      # values:
        # - "somesite"
      # reportableType: "ON" # optional, defaults to "OFF", choices: "ON", "OFF", "CUSTOM_DIMENSION"
  placement_names: # list of names (optional)
    - "Prebid Inventory"
#     - "placement name 2"
#   ad_unit_names: # list of names (optional)
#     - "ad unit name 1"
#     - "ad unit name 2"
###############################################################################


```
